name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: "CI Build"
    uses: ./.github/workflows/laravel-build.yaml

  test:
    name: "CI Unit Testing"
    needs: [build]
    uses: ./.github/workflows/laravel-unit-testing.yaml

  scan:
    name: "CI Code Scan"
    needs: [test]
    uses: ./.github/workflows/sonar-scan.yaml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
