name: CI

on:
  pull_request:
    branches:
      - dev
    types: [ assigned, opened, synchronize, reopened ]

concurrency: ci

jobs:
  build:
    name: "CI Build"
    uses: ./.github/workflows/laravel-build.yaml
    with:
      cache_key: vendor-${{ github.sha }}

  test:
    name: "CI Unit Testing"
    needs: [build]
    uses: ./.github/workflows/laravel-unit-testing.yaml
    with:
      cache_key: vendor-${{ github.sha }}

  scan:
    name: "CI Code Scan"
    needs: [test]
    uses: ./.github/workflows/sonar-scan.yaml
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
