name: "Unit Testing Laravel App"

on:
  workflow_call:

jobs:
  test:
    name: "Unit Testing"
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v4
        name: Checkout the code to Runner

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        run: composer install

      - name: Copy ENV Laravel Configuration for CI
        run: |
          cp .env.ci .env.testing
          cp .env.ci .env

      - name: Generate key
        run: php artisan key:generate --env=testing

      - name: Migrate
        run: php artisan migrate --env=testing

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
