name: Release

on:
  push:
  pull_request:
    branches:
      - main

concurrency: release

jobs:
  # build:
  #   name: "Release Build"
  #   uses: ./.github/workflows/laravel-build.yaml
  #   with:
  #     cache_key: vendor-${{ github.sha }}

  # test:
  #   name: "Release Unit Testing"
  #   needs: [build]
  #   uses: ./.github/workflows/laravel-unit-testing.yaml
  #   with:
  #     cache_key: vendor-${{ github.sha }}

  # scan:
  #   name: "Release Code Scan"
  #   needs: [test]
  #   uses: ./.github/workflows/sonar-scan.yaml
  #   secrets:
  #     gh_token: ${{ secrets.GITHUB_TOKEN }}
  #     sonar_token: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: "Build Docker images"
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-region: aws-region-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  tag:
    name: "Create Tag"
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: Checkout the code to Runner

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
